POST http://192.168.0.76:1400/MediaRenderer/AVTransport/Control HTTP/1.1
SOAPAction: urn:schemas-upnp-org:service:AVTransport:1#GetTransportInfo

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:GetTransportInfo xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
      <InstanceID>0</InstanceID>
    </u:GetTransportInfo>
  </u:Body>
</s:Envelope>