POST http://192.168.0.7:1400/MediaRenderer/AVTransport/Control HTTP/1.1
SOAPAction: urn:schemas-upnp-org:service:AVTransport:1#SetAVTransportURI

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:SetAVTransportURI xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
      <InstanceID>0</InstanceID>
      <CurrentURI>x-rincon-mp3radio://https://orf-live.ors-shoutcast.at/wie-q2a</CurrentURI>
      <CurrentURIMetaData>
      &lt;DIDL-Lite 
        xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; 
        xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; 
        xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; 
        xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;&lt;item id=&quot;-1&quot; parentID=&quot;-1&quot; restricted=&quot;true&quot;&gt;&lt;dc:title&gt;Radio Wien&lt;/dc:title&gt; &lt;upnp:albumArtURI&gt;https://cdn-profiles.tunein.com/s44255/images/logod.jpg&lt;/upnp:albumArtURI&gt;  &lt;upnp:class&gt;object.item.audioItem.audioBroadcast&lt;/upnp:class&gt;&lt;desc id=&quot;cdudn&quot; nameSpace=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot;&gt;SA_RINCON65031_&lt;/desc&gt;&lt;/item&gt;&lt;/DIDL-Lite&gt;
        
      </CurrentURIMetaData>
    </u:SetAVTransportURI>
  </u:Body>
</s:Envelope>