POST http://192.168.0.76:1400/MediaRenderer/RenderingControl/Control HTTP/1.1
SOAPAction: urn:schemas-upnp-org:service:RenderingControl:1#SetLoudness

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
  <s:Body>
    <u:SetLoudness xmlns:u="urn:schemas-upnp-org:service:RenderingControl:1">
        <InstanceID>0</InstanceID>
        <Channel>Master</Channel>
        <DesiredLoudness>1</DesiredLoudness>
    </u:SetLoudness>
  </u:Body>
</s:Envelope>